import { hasGrantedAllScopesGoogle, useGoogleLogin } from "@react-oauth/google";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
    const onSuccessesHandler = async (params) => {
        console.log("params: ", params);
        const hasAccess = checkAccess(params);
        console.log("hasAccess: ", hasAccess);
        const res = await fetch(
            "http://localhost:8000/api/google-calender/add-event",
            {
                method: "POST",
                headers: {
                    Accept: "application/json",
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    code: params.code,
                    startTimestamp: Date.now() / 1000 + 86400,
                    frequencyInDays: 3,
                    rounds: 3,
                    description: "100 USDC thrift commitment",
                }),
            }
        );

        console.log("calender: ", res);
    };
    const onFailureHandler = (params) => {
        console.log("params: ", params);
    };

    const checkAccess = (tokenResponse) => {
        return hasGrantedAllScopesGoogle(
            tokenResponse,
            "openid",
            "email",
            "profile",
            "https://www.googleapis.com/auth/calendar"
        );
    };

    const googleLogin = useGoogleLogin({
        flow: "auth-code",
        scope: "openid email profile https://www.googleapis.com/auth/calendar",
        onSuccess: onSuccessesHandler,
        onError: onFailureHandler,
    });
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                <div>
                    <button onClick={() => googleLogin()}>
                        Autenticate & add event
                    </button>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
